spring:
  application:
    name: hhn
  datasource:
    url: jdbc:mysql://localhost:3306/hhn
    username: root
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt: # 시크릿 난수 생성 터미널 명령어 : openssl rand -base64 64
  secret: "XLsJxKSTztZmOcjPj8qQNZpirpiuW3uPTuPeAI/ZkWMRvUGf+yi3VwnrLst8/WMRj1VBKHA0AQ2hYVNubcL8Tw=="
  access-expire-millis: 900000 # 15분 -> ms
  refresh-expire-millis: 86400000 # 1일 1 * 24 * 60 * 60 * 1000

mybatis:
  mapper-locations: classpath:mappers/*.xml # mapper의 경로지정
  type-aliases-package: com.koreait.spring_boot_study.entity # entity들 경로지정